# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('num_of_imports', models.IntegerField(default=1)),
            ],
        ),
    ]
