# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 05:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('last_refreshed', models.DateTimeField(default=datetime.datetime(2017, 4, 7, 5, 43, 23, 517932, tzinfo=utc))),
                ('num_of_imports', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
