# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 06:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_auto_20170407_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 6, 16, 6, 962743, tzinfo=utc)),
        ),
    ]
