# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_interest_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='author',
            new_name='creator',
        ),
    ]
