# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_auto_20170203_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
