# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0009_auto_20170303_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 25, 5, 51, 27, 807980, tzinfo=utc)),
        ),
    ]
