# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0010_auto_20170324_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 25, 9, 3, 28, 587083, tzinfo=utc)),
        ),
    ]
