# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0011_auto_20170325_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 26, 8, 15, 15, 143832, tzinfo=utc)),
        ),
    ]
