# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsitems', '0005_auto_20170402_0121'),
        ('interests', '0013_auto_20170326_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='news_results',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='newsresults', to='newsitems.NewsResult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 8, 21, 0, 819702, tzinfo=utc)),
        ),
    ]
