# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0015_auto_20170402_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 8, 30, 31, 121144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='interest',
            name='news_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsresults', to='newsitems.NewsResult'),
        ),
    ]
