# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0016_auto_20170402_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 8, 37, 45, 504349, tzinfo=utc)),
        ),
    ]
