# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=350)),
                ('top_img', models.URLField(default='', max_length=350)),
                ('source', models.CharField(default='N/A', max_length=40)),
                ('keywords', models.CharField(default='', max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 4, 7, 5, 43, 23, 517932, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='NewsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsresults', to='interests.Interest')),
                ('newsitems', models.ManyToManyField(to='newsitems.NewsItem')),
            ],
        ),
    ]
