# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0007_auto_20170210_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('link', models.URLField(max_length=300)),
                ('top_img', models.URLField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NewsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsresults', to='interests.Interest')),
                ('newsitems', models.ManyToManyField(to='newsitems.NewsItem')),
            ],
        ),
    ]
