# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsitems', '0002_newsitem_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='descr',
            new_name='description',
        ),
    ]
