# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsitems', '0003_auto_20170325_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 6, 31, 4, 573246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='top_img',
            field=models.URLField(default='', max_length=350),
        ),
    ]
